source 'http://rubygems.org'

gem 'sinatra'
gem 'activerecord', '~> 5.2'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'pg'
gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem 'tux'
gem 'faker'
gem 'json'
gem "rack-contrib", "~> 2.3"
gem "rack-cors", "~> 1.1"
gem "sqlite3"
group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'rack-test'
end