# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

Rails.application.load_tasks

desc "drops ,creates, migrates, seeds database"
task :reset_db do
    system "rails db:drop db:create db:migrate db:seed"
end
